[phases.setup]
nixPkgs = ["php81", "composer"]

[phases.build]
commands = ["composer install --optimize-autoloader --no-dev"]

[phases.start]
commands = ["php artisan serve --host=0.0.0.0 --port=8000"]